name: 'Copilot Setup Steps'

# Automatically run the setup steps when they are changed to allow for easy validation
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # Copilot will clone the repository automatically after setup completes
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/node-install
        with:
          node-version: '22.20.0'
          pnpm-version: '10.18.0'

      # Note: Type generation requires the backend to be running,
      # so it's not practical in this setup phase.
      # Copilot will need to run `pnpm generate-types` when making API changes.

      - name: Run lint check to ensure environment is properly configured
        run: pnpm lint:fix

      - name: Verify build environment
        run: pnpm typecheck

      - name: Display environment info
        run: |
          echo "=== Environment Setup Complete ==="
          echo "Node.js version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"
          echo "=== Project structure ready for Copilot ==="
